/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atena.telas;

import atena.usuario.Usuario;
import atena.usuario.UsuarioDAO;
import atena.usuario.UsuarioTableModel;
import atena.util.Util;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Adriano Lima
 */
public class CadastroGabarito extends javax.swing.JDialog {

    Usuario usuario = new Usuario();
    UsuarioDAO usuarioDAO = new UsuarioDAO();

    /**
     * Creates new form TelaCadastroUsuario
     */
    public CadastroGabarito(java.awt.Frame parent, boolean modal) {
        initComponents();
        getRootPane().setDefaultButton(btSalvar);

        btLimparActionPerformed(null);
        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNomeUsuario = new javax.swing.JLabel();
        quest10 = new javax.swing.JTextField();
        btVoltar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        quest19 = new javax.swing.JTextField();
        jlNomeUsuario3 = new javax.swing.JLabel();
        jLObrigatorioNome3 = new javax.swing.JLabel();
        jlNomeUsuario4 = new javax.swing.JLabel();
        jLObrigatorioNome4 = new javax.swing.JLabel();
        quest28 = new javax.swing.JTextField();
        quest01 = new javax.swing.JTextField();
        jlNomeUsuario2 = new javax.swing.JLabel();
        jLObrigatorioNome2 = new javax.swing.JLabel();
        btLimpar = new javax.swing.JButton();
        jLObrigatorioNome = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        jlNomeUsuario5 = new javax.swing.JLabel();
        jLObrigatorioNome5 = new javax.swing.JLabel();
        quest20 = new javax.swing.JTextField();
        quest11 = new javax.swing.JTextField();
        jlNomeUsuario6 = new javax.swing.JLabel();
        jLObrigatorioNome6 = new javax.swing.JLabel();
        quest02 = new javax.swing.JTextField();
        jLObrigatorioNome7 = new javax.swing.JLabel();
        jlNomeUsuario7 = new javax.swing.JLabel();
        quest37 = new javax.swing.JTextField();
        jLObrigatorioNome8 = new javax.swing.JLabel();
        jlNomeUsuario8 = new javax.swing.JLabel();
        quest03 = new javax.swing.JTextField();
        quest12 = new javax.swing.JTextField();
        quest21 = new javax.swing.JTextField();
        quest22 = new javax.swing.JTextField();
        quest13 = new javax.swing.JTextField();
        quest04 = new javax.swing.JTextField();
        jlNomeUsuario9 = new javax.swing.JLabel();
        quest30 = new javax.swing.JTextField();
        jlNomeUsuario10 = new javax.swing.JLabel();
        quest39 = new javax.swing.JTextField();
        jLObrigatorioNome9 = new javax.swing.JLabel();
        jLObrigatorioNome10 = new javax.swing.JLabel();
        jlNomeUsuario11 = new javax.swing.JLabel();
        jLObrigatorioNome11 = new javax.swing.JLabel();
        jlNomeUsuario12 = new javax.swing.JLabel();
        jLObrigatorioNome12 = new javax.swing.JLabel();
        jLObrigatorioNome13 = new javax.swing.JLabel();
        jlNomeUsuario13 = new javax.swing.JLabel();
        jLObrigatorioNome14 = new javax.swing.JLabel();
        jLObrigatorioNome15 = new javax.swing.JLabel();
        jLObrigatorioNome16 = new javax.swing.JLabel();
        jlNomeUsuario14 = new javax.swing.JLabel();
        jlNomeUsuario15 = new javax.swing.JLabel();
        jlNomeUsuario16 = new javax.swing.JLabel();
        jlNomeUsuario17 = new javax.swing.JLabel();
        jLObrigatorioNome17 = new javax.swing.JLabel();
        jLObrigatorioNome18 = new javax.swing.JLabel();
        quest25 = new javax.swing.JTextField();
        jLObrigatorioNome19 = new javax.swing.JLabel();
        jlNomeUsuario18 = new javax.swing.JLabel();
        quest07 = new javax.swing.JTextField();
        quest16 = new javax.swing.JTextField();
        jLObrigatorioNome20 = new javax.swing.JLabel();
        quest26 = new javax.swing.JTextField();
        jLObrigatorioNome21 = new javax.swing.JLabel();
        jLObrigatorioNome22 = new javax.swing.JLabel();
        jlNomeUsuario19 = new javax.swing.JLabel();
        quest08 = new javax.swing.JTextField();
        quest17 = new javax.swing.JTextField();
        jLObrigatorioNome23 = new javax.swing.JLabel();
        jlNomeUsuario20 = new javax.swing.JLabel();
        jlNomeUsuario21 = new javax.swing.JLabel();
        jLObrigatorioNome24 = new javax.swing.JLabel();
        jlNomeUsuario22 = new javax.swing.JLabel();
        quest43 = new javax.swing.JTextField();
        jlNomeUsuario23 = new javax.swing.JLabel();
        quest34 = new javax.swing.JTextField();
        jlNomeUsuario24 = new javax.swing.JLabel();
        jlNomeUsuario25 = new javax.swing.JLabel();
        jLObrigatorioNome25 = new javax.swing.JLabel();
        quest06 = new javax.swing.JTextField();
        jlNomeUsuario26 = new javax.swing.JLabel();
        jLObrigatorioNome26 = new javax.swing.JLabel();
        quest15 = new javax.swing.JTextField();
        jlNomeUsuario27 = new javax.swing.JLabel();
        jLObrigatorioNome27 = new javax.swing.JLabel();
        quest24 = new javax.swing.JTextField();
        quest32 = new javax.swing.JTextField();
        quest41 = new javax.swing.JTextField();
        jLObrigatorioNome28 = new javax.swing.JLabel();
        jlNomeUsuario28 = new javax.swing.JLabel();
        jlNomeUsuario29 = new javax.swing.JLabel();
        quest23 = new javax.swing.JTextField();
        jLObrigatorioNome29 = new javax.swing.JLabel();
        jlNomeUsuario30 = new javax.swing.JLabel();
        quest14 = new javax.swing.JTextField();
        jLObrigatorioNome30 = new javax.swing.JLabel();
        jlNomeUsuario31 = new javax.swing.JLabel();
        quest05 = new javax.swing.JTextField();
        jLObrigatorioNome31 = new javax.swing.JLabel();
        jlNomeUsuario32 = new javax.swing.JLabel();
        jlNomeUsuario33 = new javax.swing.JLabel();
        quest29 = new javax.swing.JTextField();
        jlNomeUsuario34 = new javax.swing.JLabel();
        quest38 = new javax.swing.JTextField();
        jLObrigatorioNome32 = new javax.swing.JLabel();
        jLObrigatorioNome33 = new javax.swing.JLabel();
        jlNomeUsuario35 = new javax.swing.JLabel();
        quest31 = new javax.swing.JTextField();
        jlNomeUsuario36 = new javax.swing.JLabel();
        quest40 = new javax.swing.JTextField();
        jLObrigatorioNome34 = new javax.swing.JLabel();
        jLObrigatorioNome35 = new javax.swing.JLabel();
        jlNomeUsuario37 = new javax.swing.JLabel();
        quest33 = new javax.swing.JTextField();
        jlNomeUsuario38 = new javax.swing.JLabel();
        quest42 = new javax.swing.JTextField();
        jLObrigatorioNome36 = new javax.swing.JLabel();
        jLObrigatorioNome37 = new javax.swing.JLabel();
        jlNomeUsuario39 = new javax.swing.JLabel();
        quest35 = new javax.swing.JTextField();
        jlNomeUsuario40 = new javax.swing.JLabel();
        quest44 = new javax.swing.JTextField();
        jLObrigatorioNome38 = new javax.swing.JLabel();
        jLObrigatorioNome39 = new javax.swing.JLabel();
        jlNomeUsuario41 = new javax.swing.JLabel();
        jLObrigatorioNome40 = new javax.swing.JLabel();
        quest09 = new javax.swing.JTextField();
        jlNomeUsuario42 = new javax.swing.JLabel();
        jLObrigatorioNome41 = new javax.swing.JLabel();
        quest18 = new javax.swing.JTextField();
        jlNomeUsuario43 = new javax.swing.JLabel();
        jLObrigatorioNome42 = new javax.swing.JLabel();
        quest27 = new javax.swing.JTextField();
        jlNomeUsuario44 = new javax.swing.JLabel();
        jLObrigatorioNome43 = new javax.swing.JLabel();
        quest36 = new javax.swing.JTextField();
        jLObrigatorioNome45 = new javax.swing.JLabel();
        jlNomeUsuario45 = new javax.swing.JLabel();
        jLObrigatorioNome44 = new javax.swing.JLabel();
        quest45 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(855, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(855, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jlNomeUsuario.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario.setText("10");
        getContentPane().add(jlNomeUsuario);
        jlNomeUsuario.setBounds(40, 210, 30, 20);

        quest10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest10.setMaximumSize(new java.awt.Dimension(8, 200));
        quest10.setMinimumSize(new java.awt.Dimension(8, 200));
        quest10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest10ActionPerformed(evt);
            }
        });
        getContentPane().add(quest10);
        quest10.setBounds(40, 230, 60, 30);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/return.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setContentAreaFilled(false);
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar);
        btVoltar.setBounds(10, 520, 90, 70);

        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/search.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.setContentAreaFilled(false);
        btPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisar);
        btPesquisar.setBounds(370, 520, 99, 70);

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/delete.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setContentAreaFilled(false);
        btExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir);
        btExcluir.setBounds(530, 520, 80, 70);

        quest19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest19.setMaximumSize(new java.awt.Dimension(8, 200));
        quest19.setMinimumSize(new java.awt.Dimension(8, 200));
        quest19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest19ActionPerformed(evt);
            }
        });
        getContentPane().add(quest19);
        quest19.setBounds(40, 290, 60, 30);

        jlNomeUsuario3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario3.setText("19");
        getContentPane().add(jlNomeUsuario3);
        jlNomeUsuario3.setBounds(40, 270, 30, 20);

        jLObrigatorioNome3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome3.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome3.setText("*");
        getContentPane().add(jLObrigatorioNome3);
        jLObrigatorioNome3.setBounds(90, 280, 10, 10);

        jlNomeUsuario4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario4.setText("28");
        getContentPane().add(jlNomeUsuario4);
        jlNomeUsuario4.setBounds(40, 330, 30, 20);

        jLObrigatorioNome4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome4.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome4.setText("*");
        getContentPane().add(jLObrigatorioNome4);
        jLObrigatorioNome4.setBounds(90, 340, 10, 10);

        quest28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest28.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest28.setMaximumSize(new java.awt.Dimension(8, 200));
        quest28.setMinimumSize(new java.awt.Dimension(8, 200));
        quest28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest28ActionPerformed(evt);
            }
        });
        getContentPane().add(quest28);
        quest28.setBounds(40, 350, 60, 30);

        quest01.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest01.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest01.setMaximumSize(new java.awt.Dimension(8, 200));
        quest01.setMinimumSize(new java.awt.Dimension(8, 200));
        quest01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest01ActionPerformed(evt);
            }
        });
        getContentPane().add(quest01);
        quest01.setBounds(40, 170, 60, 30);

        jlNomeUsuario2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario2.setText("01");
        getContentPane().add(jlNomeUsuario2);
        jlNomeUsuario2.setBounds(40, 150, 30, 20);

        jLObrigatorioNome2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome2.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome2.setText("*");
        getContentPane().add(jLObrigatorioNome2);
        jLObrigatorioNome2.setBounds(90, 160, 10, 10);

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/clean.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setContentAreaFilled(false);
        btLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar);
        btLimpar.setBounds(220, 520, 80, 70);

        jLObrigatorioNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome.setText("*");
        getContentPane().add(jLObrigatorioNome);
        jLObrigatorioNome.setBounds(90, 220, 10, 10);

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/save.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setContentAreaFilled(false);
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar);
        btSalvar.setBounds(760, 520, 80, 70);

        jlNomeUsuario5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario5.setText("11");
        getContentPane().add(jlNomeUsuario5);
        jlNomeUsuario5.setBounds(130, 210, 30, 20);

        jLObrigatorioNome5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome5.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome5.setText("*");
        getContentPane().add(jLObrigatorioNome5);
        jLObrigatorioNome5.setBounds(180, 280, 10, 10);

        quest20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest20.setMaximumSize(new java.awt.Dimension(8, 200));
        quest20.setMinimumSize(new java.awt.Dimension(8, 200));
        quest20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest20ActionPerformed(evt);
            }
        });
        getContentPane().add(quest20);
        quest20.setBounds(130, 290, 60, 30);

        quest11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest11.setMaximumSize(new java.awt.Dimension(8, 200));
        quest11.setMinimumSize(new java.awt.Dimension(8, 200));
        quest11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest11ActionPerformed(evt);
            }
        });
        getContentPane().add(quest11);
        quest11.setBounds(130, 230, 60, 30);

        jlNomeUsuario6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario6.setText("20");
        getContentPane().add(jlNomeUsuario6);
        jlNomeUsuario6.setBounds(130, 270, 30, 20);

        jLObrigatorioNome6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome6.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome6.setText("*");
        getContentPane().add(jLObrigatorioNome6);
        jLObrigatorioNome6.setBounds(180, 220, 10, 10);

        quest02.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest02.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest02.setMaximumSize(new java.awt.Dimension(8, 200));
        quest02.setMinimumSize(new java.awt.Dimension(8, 200));
        quest02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest02ActionPerformed(evt);
            }
        });
        getContentPane().add(quest02);
        quest02.setBounds(130, 170, 60, 30);

        jLObrigatorioNome7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome7.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome7.setText("*");
        getContentPane().add(jLObrigatorioNome7);
        jLObrigatorioNome7.setBounds(180, 160, 10, 10);

        jlNomeUsuario7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario7.setText("02");
        getContentPane().add(jlNomeUsuario7);
        jlNomeUsuario7.setBounds(130, 150, 30, 20);

        quest37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest37.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest37.setMaximumSize(new java.awt.Dimension(8, 200));
        quest37.setMinimumSize(new java.awt.Dimension(8, 200));
        quest37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest37ActionPerformed(evt);
            }
        });
        getContentPane().add(quest37);
        quest37.setBounds(40, 410, 60, 30);

        jLObrigatorioNome8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome8.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome8.setText("*");
        getContentPane().add(jLObrigatorioNome8);
        jLObrigatorioNome8.setBounds(90, 400, 10, 10);

        jlNomeUsuario8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario8.setText("37");
        getContentPane().add(jlNomeUsuario8);
        jlNomeUsuario8.setBounds(40, 390, 30, 20);

        quest03.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest03.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest03.setMaximumSize(new java.awt.Dimension(8, 200));
        quest03.setMinimumSize(new java.awt.Dimension(8, 200));
        quest03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest03ActionPerformed(evt);
            }
        });
        getContentPane().add(quest03);
        quest03.setBounds(220, 170, 60, 30);

        quest12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest12.setMaximumSize(new java.awt.Dimension(8, 200));
        quest12.setMinimumSize(new java.awt.Dimension(8, 200));
        quest12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest12ActionPerformed(evt);
            }
        });
        getContentPane().add(quest12);
        quest12.setBounds(220, 230, 60, 30);

        quest21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest21.setMaximumSize(new java.awt.Dimension(8, 200));
        quest21.setMinimumSize(new java.awt.Dimension(8, 200));
        quest21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest21ActionPerformed(evt);
            }
        });
        getContentPane().add(quest21);
        quest21.setBounds(220, 290, 60, 30);

        quest22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest22.setMaximumSize(new java.awt.Dimension(8, 200));
        quest22.setMinimumSize(new java.awt.Dimension(8, 200));
        quest22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest22ActionPerformed(evt);
            }
        });
        getContentPane().add(quest22);
        quest22.setBounds(310, 290, 60, 30);

        quest13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest13.setMaximumSize(new java.awt.Dimension(8, 200));
        quest13.setMinimumSize(new java.awt.Dimension(8, 200));
        quest13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest13ActionPerformed(evt);
            }
        });
        getContentPane().add(quest13);
        quest13.setBounds(310, 230, 60, 30);

        quest04.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest04.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest04.setMaximumSize(new java.awt.Dimension(8, 200));
        quest04.setMinimumSize(new java.awt.Dimension(8, 200));
        quest04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest04ActionPerformed(evt);
            }
        });
        getContentPane().add(quest04);
        quest04.setBounds(310, 170, 60, 30);

        jlNomeUsuario9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario9.setText("30");
        getContentPane().add(jlNomeUsuario9);
        jlNomeUsuario9.setBounds(220, 330, 30, 20);

        quest30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest30.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest30.setMaximumSize(new java.awt.Dimension(8, 200));
        quest30.setMinimumSize(new java.awt.Dimension(8, 200));
        quest30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest30ActionPerformed(evt);
            }
        });
        getContentPane().add(quest30);
        quest30.setBounds(220, 350, 60, 30);

        jlNomeUsuario10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario10.setText("39");
        getContentPane().add(jlNomeUsuario10);
        jlNomeUsuario10.setBounds(220, 390, 30, 20);

        quest39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest39.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest39.setMaximumSize(new java.awt.Dimension(8, 200));
        quest39.setMinimumSize(new java.awt.Dimension(8, 200));
        quest39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest39ActionPerformed(evt);
            }
        });
        getContentPane().add(quest39);
        quest39.setBounds(220, 410, 60, 30);

        jLObrigatorioNome9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome9.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome9.setText("*");
        getContentPane().add(jLObrigatorioNome9);
        jLObrigatorioNome9.setBounds(270, 400, 10, 10);

        jLObrigatorioNome10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome10.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome10.setText("*");
        getContentPane().add(jLObrigatorioNome10);
        jLObrigatorioNome10.setBounds(270, 340, 10, 10);

        jlNomeUsuario11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario11.setText("21");
        getContentPane().add(jlNomeUsuario11);
        jlNomeUsuario11.setBounds(220, 270, 30, 20);

        jLObrigatorioNome11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome11.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome11.setText("*");
        getContentPane().add(jLObrigatorioNome11);
        jLObrigatorioNome11.setBounds(270, 280, 10, 10);

        jlNomeUsuario12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario12.setText("12");
        getContentPane().add(jlNomeUsuario12);
        jlNomeUsuario12.setBounds(220, 210, 30, 20);

        jLObrigatorioNome12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome12.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome12.setText("*");
        getContentPane().add(jLObrigatorioNome12);
        jLObrigatorioNome12.setBounds(270, 220, 10, 10);

        jLObrigatorioNome13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome13.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome13.setText("*");
        getContentPane().add(jLObrigatorioNome13);
        jLObrigatorioNome13.setBounds(270, 160, 10, 10);

        jlNomeUsuario13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario13.setText("03");
        getContentPane().add(jlNomeUsuario13);
        jlNomeUsuario13.setBounds(220, 150, 30, 20);

        jLObrigatorioNome14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome14.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome14.setText("*");
        getContentPane().add(jLObrigatorioNome14);
        jLObrigatorioNome14.setBounds(360, 160, 10, 10);

        jLObrigatorioNome15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome15.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome15.setText("*");
        getContentPane().add(jLObrigatorioNome15);
        jLObrigatorioNome15.setBounds(360, 220, 10, 10);

        jLObrigatorioNome16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome16.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome16.setText("*");
        getContentPane().add(jLObrigatorioNome16);
        jLObrigatorioNome16.setBounds(360, 280, 10, 10);

        jlNomeUsuario14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario14.setText("22");
        getContentPane().add(jlNomeUsuario14);
        jlNomeUsuario14.setBounds(310, 270, 30, 20);

        jlNomeUsuario15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario15.setText("13");
        getContentPane().add(jlNomeUsuario15);
        jlNomeUsuario15.setBounds(310, 210, 30, 20);

        jlNomeUsuario16.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario16.setText("04");
        getContentPane().add(jlNomeUsuario16);
        jlNomeUsuario16.setBounds(310, 150, 30, 20);

        jlNomeUsuario17.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario17.setText("16");
        getContentPane().add(jlNomeUsuario17);
        jlNomeUsuario17.setBounds(580, 210, 30, 20);

        jLObrigatorioNome17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome17.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome17.setText("*");
        getContentPane().add(jLObrigatorioNome17);
        jLObrigatorioNome17.setBounds(720, 160, 10, 10);

        jLObrigatorioNome18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome18.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome18.setText("*");
        getContentPane().add(jLObrigatorioNome18);
        jLObrigatorioNome18.setBounds(630, 280, 10, 10);

        quest25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest25.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest25.setMaximumSize(new java.awt.Dimension(8, 200));
        quest25.setMinimumSize(new java.awt.Dimension(8, 200));
        quest25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest25ActionPerformed(evt);
            }
        });
        getContentPane().add(quest25);
        quest25.setBounds(580, 290, 60, 30);

        jLObrigatorioNome19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome19.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome19.setText("*");
        getContentPane().add(jLObrigatorioNome19);
        jLObrigatorioNome19.setBounds(630, 340, 10, 10);

        jlNomeUsuario18.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario18.setText("07");
        getContentPane().add(jlNomeUsuario18);
        jlNomeUsuario18.setBounds(580, 150, 30, 20);

        quest07.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest07.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest07.setMaximumSize(new java.awt.Dimension(8, 200));
        quest07.setMinimumSize(new java.awt.Dimension(8, 200));
        quest07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest07ActionPerformed(evt);
            }
        });
        getContentPane().add(quest07);
        quest07.setBounds(580, 170, 60, 30);

        quest16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest16.setMaximumSize(new java.awt.Dimension(8, 200));
        quest16.setMinimumSize(new java.awt.Dimension(8, 200));
        quest16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest16ActionPerformed(evt);
            }
        });
        getContentPane().add(quest16);
        quest16.setBounds(580, 230, 60, 30);

        jLObrigatorioNome20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome20.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome20.setText("*");
        getContentPane().add(jLObrigatorioNome20);
        jLObrigatorioNome20.setBounds(720, 220, 10, 10);

        quest26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest26.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest26.setMaximumSize(new java.awt.Dimension(8, 200));
        quest26.setMinimumSize(new java.awt.Dimension(8, 200));
        quest26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest26ActionPerformed(evt);
            }
        });
        getContentPane().add(quest26);
        quest26.setBounds(670, 290, 60, 30);

        jLObrigatorioNome21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome21.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome21.setText("*");
        getContentPane().add(jLObrigatorioNome21);
        jLObrigatorioNome21.setBounds(630, 220, 10, 10);

        jLObrigatorioNome22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome22.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome22.setText("*");
        getContentPane().add(jLObrigatorioNome22);
        jLObrigatorioNome22.setBounds(630, 160, 10, 10);

        jlNomeUsuario19.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario19.setText("17");
        getContentPane().add(jlNomeUsuario19);
        jlNomeUsuario19.setBounds(670, 210, 30, 20);

        quest08.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest08.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest08.setMaximumSize(new java.awt.Dimension(8, 200));
        quest08.setMinimumSize(new java.awt.Dimension(8, 200));
        quest08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest08ActionPerformed(evt);
            }
        });
        getContentPane().add(quest08);
        quest08.setBounds(670, 170, 60, 30);

        quest17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest17.setMaximumSize(new java.awt.Dimension(8, 200));
        quest17.setMinimumSize(new java.awt.Dimension(8, 200));
        quest17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest17ActionPerformed(evt);
            }
        });
        getContentPane().add(quest17);
        quest17.setBounds(670, 230, 60, 30);

        jLObrigatorioNome23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome23.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome23.setText("*");
        getContentPane().add(jLObrigatorioNome23);
        jLObrigatorioNome23.setBounds(630, 400, 10, 10);

        jlNomeUsuario20.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario20.setText("34");
        getContentPane().add(jlNomeUsuario20);
        jlNomeUsuario20.setBounds(580, 330, 30, 20);

        jlNomeUsuario21.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario21.setText("25");
        getContentPane().add(jlNomeUsuario21);
        jlNomeUsuario21.setBounds(580, 270, 30, 20);

        jLObrigatorioNome24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome24.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome24.setText("*");
        getContentPane().add(jLObrigatorioNome24);
        jLObrigatorioNome24.setBounds(720, 280, 10, 10);

        jlNomeUsuario22.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario22.setText("26");
        getContentPane().add(jlNomeUsuario22);
        jlNomeUsuario22.setBounds(670, 270, 30, 20);

        quest43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest43.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest43.setMaximumSize(new java.awt.Dimension(8, 200));
        quest43.setMinimumSize(new java.awt.Dimension(8, 200));
        quest43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest43ActionPerformed(evt);
            }
        });
        getContentPane().add(quest43);
        quest43.setBounds(580, 410, 60, 30);

        jlNomeUsuario23.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario23.setText("08");
        getContentPane().add(jlNomeUsuario23);
        jlNomeUsuario23.setBounds(670, 150, 30, 20);

        quest34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest34.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest34.setMaximumSize(new java.awt.Dimension(8, 200));
        quest34.setMinimumSize(new java.awt.Dimension(8, 200));
        quest34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest34ActionPerformed(evt);
            }
        });
        getContentPane().add(quest34);
        quest34.setBounds(580, 350, 60, 30);

        jlNomeUsuario24.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario24.setText("43");
        getContentPane().add(jlNomeUsuario24);
        jlNomeUsuario24.setBounds(580, 390, 30, 20);

        jlNomeUsuario25.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario25.setText("06");
        getContentPane().add(jlNomeUsuario25);
        jlNomeUsuario25.setBounds(490, 150, 30, 20);

        jLObrigatorioNome25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome25.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome25.setText("*");
        getContentPane().add(jLObrigatorioNome25);
        jLObrigatorioNome25.setBounds(540, 160, 10, 10);

        quest06.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest06.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest06.setMaximumSize(new java.awt.Dimension(8, 200));
        quest06.setMinimumSize(new java.awt.Dimension(8, 200));
        quest06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest06ActionPerformed(evt);
            }
        });
        getContentPane().add(quest06);
        quest06.setBounds(490, 170, 60, 30);

        jlNomeUsuario26.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario26.setText("15");
        getContentPane().add(jlNomeUsuario26);
        jlNomeUsuario26.setBounds(490, 210, 30, 20);

        jLObrigatorioNome26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome26.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome26.setText("*");
        getContentPane().add(jLObrigatorioNome26);
        jLObrigatorioNome26.setBounds(540, 220, 10, 10);

        quest15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest15.setMaximumSize(new java.awt.Dimension(8, 200));
        quest15.setMinimumSize(new java.awt.Dimension(8, 200));
        quest15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest15ActionPerformed(evt);
            }
        });
        getContentPane().add(quest15);
        quest15.setBounds(490, 230, 60, 30);

        jlNomeUsuario27.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario27.setText("24");
        getContentPane().add(jlNomeUsuario27);
        jlNomeUsuario27.setBounds(490, 270, 30, 20);

        jLObrigatorioNome27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome27.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome27.setText("*");
        getContentPane().add(jLObrigatorioNome27);
        jLObrigatorioNome27.setBounds(540, 280, 10, 10);

        quest24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest24.setMaximumSize(new java.awt.Dimension(8, 200));
        quest24.setMinimumSize(new java.awt.Dimension(8, 200));
        quest24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest24ActionPerformed(evt);
            }
        });
        getContentPane().add(quest24);
        quest24.setBounds(490, 290, 60, 30);

        quest32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest32.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest32.setMaximumSize(new java.awt.Dimension(8, 200));
        quest32.setMinimumSize(new java.awt.Dimension(8, 200));
        quest32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest32ActionPerformed(evt);
            }
        });
        getContentPane().add(quest32);
        quest32.setBounds(400, 350, 60, 30);

        quest41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest41.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest41.setMaximumSize(new java.awt.Dimension(8, 200));
        quest41.setMinimumSize(new java.awt.Dimension(8, 200));
        quest41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest41ActionPerformed(evt);
            }
        });
        getContentPane().add(quest41);
        quest41.setBounds(400, 410, 60, 30);

        jLObrigatorioNome28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome28.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome28.setText("*");
        getContentPane().add(jLObrigatorioNome28);
        jLObrigatorioNome28.setBounds(450, 400, 10, 10);

        jlNomeUsuario28.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario28.setText("41");
        getContentPane().add(jlNomeUsuario28);
        jlNomeUsuario28.setBounds(400, 390, 30, 20);

        jlNomeUsuario29.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario29.setText("32");
        getContentPane().add(jlNomeUsuario29);
        jlNomeUsuario29.setBounds(400, 330, 30, 20);

        quest23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest23.setMaximumSize(new java.awt.Dimension(8, 200));
        quest23.setMinimumSize(new java.awt.Dimension(8, 200));
        quest23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest23ActionPerformed(evt);
            }
        });
        getContentPane().add(quest23);
        quest23.setBounds(400, 290, 60, 30);

        jLObrigatorioNome29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome29.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome29.setText("*");
        getContentPane().add(jLObrigatorioNome29);
        jLObrigatorioNome29.setBounds(450, 280, 10, 10);

        jlNomeUsuario30.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario30.setText("23");
        getContentPane().add(jlNomeUsuario30);
        jlNomeUsuario30.setBounds(400, 270, 30, 20);

        quest14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest14.setMaximumSize(new java.awt.Dimension(8, 200));
        quest14.setMinimumSize(new java.awt.Dimension(8, 200));
        quest14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest14ActionPerformed(evt);
            }
        });
        getContentPane().add(quest14);
        quest14.setBounds(400, 230, 60, 30);

        jLObrigatorioNome30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome30.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome30.setText("*");
        getContentPane().add(jLObrigatorioNome30);
        jLObrigatorioNome30.setBounds(450, 220, 10, 10);

        jlNomeUsuario31.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario31.setText("14");
        getContentPane().add(jlNomeUsuario31);
        jlNomeUsuario31.setBounds(400, 210, 30, 20);

        quest05.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest05.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest05.setMaximumSize(new java.awt.Dimension(8, 200));
        quest05.setMinimumSize(new java.awt.Dimension(8, 200));
        quest05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest05ActionPerformed(evt);
            }
        });
        getContentPane().add(quest05);
        quest05.setBounds(400, 170, 60, 30);

        jLObrigatorioNome31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome31.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome31.setText("*");
        getContentPane().add(jLObrigatorioNome31);
        jLObrigatorioNome31.setBounds(450, 160, 10, 10);

        jlNomeUsuario32.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario32.setText("05");
        getContentPane().add(jlNomeUsuario32);
        jlNomeUsuario32.setBounds(400, 150, 30, 20);

        jlNomeUsuario33.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario33.setText("29");
        getContentPane().add(jlNomeUsuario33);
        jlNomeUsuario33.setBounds(130, 330, 30, 20);

        quest29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest29.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest29.setMaximumSize(new java.awt.Dimension(8, 200));
        quest29.setMinimumSize(new java.awt.Dimension(8, 200));
        quest29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest29ActionPerformed(evt);
            }
        });
        getContentPane().add(quest29);
        quest29.setBounds(130, 350, 60, 30);

        jlNomeUsuario34.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario34.setText("38");
        getContentPane().add(jlNomeUsuario34);
        jlNomeUsuario34.setBounds(130, 390, 30, 20);

        quest38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest38.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest38.setMaximumSize(new java.awt.Dimension(8, 200));
        quest38.setMinimumSize(new java.awt.Dimension(8, 200));
        quest38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest38ActionPerformed(evt);
            }
        });
        getContentPane().add(quest38);
        quest38.setBounds(130, 410, 60, 30);

        jLObrigatorioNome32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome32.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome32.setText("*");
        getContentPane().add(jLObrigatorioNome32);
        jLObrigatorioNome32.setBounds(180, 400, 10, 10);

        jLObrigatorioNome33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome33.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome33.setText("*");
        getContentPane().add(jLObrigatorioNome33);
        jLObrigatorioNome33.setBounds(180, 340, 10, 10);

        jlNomeUsuario35.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario35.setText("31");
        getContentPane().add(jlNomeUsuario35);
        jlNomeUsuario35.setBounds(310, 330, 30, 20);

        quest31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest31.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest31.setMaximumSize(new java.awt.Dimension(8, 200));
        quest31.setMinimumSize(new java.awt.Dimension(8, 200));
        quest31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest31ActionPerformed(evt);
            }
        });
        getContentPane().add(quest31);
        quest31.setBounds(310, 350, 60, 30);

        jlNomeUsuario36.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario36.setText("40");
        getContentPane().add(jlNomeUsuario36);
        jlNomeUsuario36.setBounds(310, 390, 30, 20);

        quest40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest40.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest40.setMaximumSize(new java.awt.Dimension(8, 200));
        quest40.setMinimumSize(new java.awt.Dimension(8, 200));
        quest40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest40ActionPerformed(evt);
            }
        });
        getContentPane().add(quest40);
        quest40.setBounds(310, 410, 60, 30);

        jLObrigatorioNome34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome34.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome34.setText("*");
        getContentPane().add(jLObrigatorioNome34);
        jLObrigatorioNome34.setBounds(360, 400, 10, 10);

        jLObrigatorioNome35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome35.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome35.setText("*");
        getContentPane().add(jLObrigatorioNome35);
        jLObrigatorioNome35.setBounds(360, 340, 10, 10);

        jlNomeUsuario37.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario37.setText("33");
        getContentPane().add(jlNomeUsuario37);
        jlNomeUsuario37.setBounds(490, 330, 30, 20);

        quest33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest33.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest33.setMaximumSize(new java.awt.Dimension(8, 200));
        quest33.setMinimumSize(new java.awt.Dimension(8, 200));
        quest33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest33ActionPerformed(evt);
            }
        });
        getContentPane().add(quest33);
        quest33.setBounds(490, 350, 60, 30);

        jlNomeUsuario38.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario38.setText("42");
        getContentPane().add(jlNomeUsuario38);
        jlNomeUsuario38.setBounds(490, 390, 30, 20);

        quest42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest42.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest42.setMaximumSize(new java.awt.Dimension(8, 200));
        quest42.setMinimumSize(new java.awt.Dimension(8, 200));
        quest42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest42ActionPerformed(evt);
            }
        });
        getContentPane().add(quest42);
        quest42.setBounds(490, 410, 60, 30);

        jLObrigatorioNome36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome36.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome36.setText("*");
        getContentPane().add(jLObrigatorioNome36);
        jLObrigatorioNome36.setBounds(450, 340, 10, 10);

        jLObrigatorioNome37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome37.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome37.setText("*");
        getContentPane().add(jLObrigatorioNome37);
        jLObrigatorioNome37.setBounds(540, 340, 10, 10);

        jlNomeUsuario39.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario39.setText("35");
        getContentPane().add(jlNomeUsuario39);
        jlNomeUsuario39.setBounds(670, 330, 30, 20);

        quest35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest35.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest35.setMaximumSize(new java.awt.Dimension(8, 200));
        quest35.setMinimumSize(new java.awt.Dimension(8, 200));
        quest35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest35ActionPerformed(evt);
            }
        });
        getContentPane().add(quest35);
        quest35.setBounds(670, 350, 60, 30);

        jlNomeUsuario40.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario40.setText("44");
        getContentPane().add(jlNomeUsuario40);
        jlNomeUsuario40.setBounds(670, 390, 30, 20);

        quest44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest44.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest44.setMaximumSize(new java.awt.Dimension(8, 200));
        quest44.setMinimumSize(new java.awt.Dimension(8, 200));
        quest44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest44ActionPerformed(evt);
            }
        });
        getContentPane().add(quest44);
        quest44.setBounds(670, 410, 60, 30);

        jLObrigatorioNome38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome38.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome38.setText("*");
        getContentPane().add(jLObrigatorioNome38);
        jLObrigatorioNome38.setBounds(720, 400, 10, 10);

        jLObrigatorioNome39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome39.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome39.setText("*");
        getContentPane().add(jLObrigatorioNome39);
        jLObrigatorioNome39.setBounds(720, 340, 10, 10);

        jlNomeUsuario41.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario41.setText("09");
        getContentPane().add(jlNomeUsuario41);
        jlNomeUsuario41.setBounds(760, 150, 30, 20);

        jLObrigatorioNome40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome40.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome40.setText("*");
        getContentPane().add(jLObrigatorioNome40);
        jLObrigatorioNome40.setBounds(810, 160, 10, 10);

        quest09.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest09.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest09.setMaximumSize(new java.awt.Dimension(8, 200));
        quest09.setMinimumSize(new java.awt.Dimension(8, 200));
        quest09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest09ActionPerformed(evt);
            }
        });
        getContentPane().add(quest09);
        quest09.setBounds(760, 170, 60, 30);

        jlNomeUsuario42.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario42.setText("18");
        getContentPane().add(jlNomeUsuario42);
        jlNomeUsuario42.setBounds(760, 210, 30, 20);

        jLObrigatorioNome41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome41.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome41.setText("*");
        getContentPane().add(jLObrigatorioNome41);
        jLObrigatorioNome41.setBounds(810, 220, 10, 10);

        quest18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest18.setMaximumSize(new java.awt.Dimension(8, 200));
        quest18.setMinimumSize(new java.awt.Dimension(8, 200));
        quest18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest18ActionPerformed(evt);
            }
        });
        getContentPane().add(quest18);
        quest18.setBounds(760, 230, 60, 30);

        jlNomeUsuario43.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario43.setText("27");
        getContentPane().add(jlNomeUsuario43);
        jlNomeUsuario43.setBounds(760, 270, 30, 20);

        jLObrigatorioNome42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome42.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome42.setText("*");
        getContentPane().add(jLObrigatorioNome42);
        jLObrigatorioNome42.setBounds(810, 280, 10, 10);

        quest27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest27.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest27.setMaximumSize(new java.awt.Dimension(8, 200));
        quest27.setMinimumSize(new java.awt.Dimension(8, 200));
        quest27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest27ActionPerformed(evt);
            }
        });
        getContentPane().add(quest27);
        quest27.setBounds(760, 290, 60, 30);

        jlNomeUsuario44.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario44.setText("36");
        getContentPane().add(jlNomeUsuario44);
        jlNomeUsuario44.setBounds(760, 330, 30, 20);

        jLObrigatorioNome43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome43.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome43.setText("*");
        getContentPane().add(jLObrigatorioNome43);
        jLObrigatorioNome43.setBounds(810, 340, 10, 10);

        quest36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest36.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest36.setMaximumSize(new java.awt.Dimension(8, 200));
        quest36.setMinimumSize(new java.awt.Dimension(8, 200));
        quest36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest36ActionPerformed(evt);
            }
        });
        getContentPane().add(quest36);
        quest36.setBounds(760, 350, 60, 30);

        jLObrigatorioNome45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome45.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome45.setText("*");
        getContentPane().add(jLObrigatorioNome45);
        jLObrigatorioNome45.setBounds(540, 400, 10, 10);

        jlNomeUsuario45.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNomeUsuario45.setText("45");
        getContentPane().add(jlNomeUsuario45);
        jlNomeUsuario45.setBounds(760, 390, 30, 20);

        jLObrigatorioNome44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome44.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome44.setText("*");
        getContentPane().add(jLObrigatorioNome44);
        jLObrigatorioNome44.setBounds(810, 400, 10, 10);

        quest45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quest45.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        quest45.setMaximumSize(new java.awt.Dimension(8, 200));
        quest45.setMinimumSize(new java.awt.Dimension(8, 200));
        quest45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quest45ActionPerformed(evt);
            }
        });
        getContentPane().add(quest45);
        quest45.setBounds(760, 410, 60, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/cad_gabarito.png"))); // NOI18N
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        jLabel6.setMaximumSize(new java.awt.Dimension(855, 600));
        jLabel6.setMinimumSize(new java.awt.Dimension(855, 600));
        jLabel6.setPreferredSize(new java.awt.Dimension(855, 600));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 855, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        List<Usuario> lista;
        lista = (usuarioDAO.listar());
        UsuarioTableModel itm = new UsuarioTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Usuario");
        if (objetoRetorno != null) {
            usuario = usuarioDAO.consultarObjetoId("idUsuario", objetoRetorno);
            quest10.setText(usuario.getNomeUsuario());
            btExcluir.setEnabled(true);
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        usuarioDAO.excluir(usuario);
        btLimparActionPerformed(null);
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        Util.limparCamposGenerico(this);
        btExcluir.setEnabled(false);
        usuario = new Usuario();

    }//GEN-LAST:event_btLimparActionPerformed

    private void travarTeclado(java.awt.event.KeyEvent evt, JTextField txt){
        int ascii = evt.getKeyChar();
        if (!(ascii >= 41 && ascii <= 45) || !(ascii >= 61 && ascii <= 65)) {
            evt.consume();
        }
        if (txt.getText().length() >= 1) {
            evt.consume();
        }
    }
    
    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

//        if (tfLogin.getText().equals("") || tfNomeUsuario.getText().equals("") || tfSenha.getText().equals("")) {
//            JOptionPane.showMessageDialog(this, "Prencha todos os campos !!");
//        } else {
//            usuario.setNomeUsuario(tfNomeUsuario.getText().toUpperCase());
//            usuarioDAO.salvar(usuario);
//            btLimparActionPerformed(null);
//
//        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed

        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void quest10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest10ActionPerformed

    private void quest01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest01ActionPerformed

    private void quest19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest19ActionPerformed

    private void quest28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest28ActionPerformed

    private void quest20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest20ActionPerformed

    private void quest11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest11ActionPerformed

    private void quest02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest02ActionPerformed

    private void quest37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest37ActionPerformed

    private void quest03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest03ActionPerformed

    private void quest12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest12ActionPerformed

    private void quest21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest21ActionPerformed

    private void quest22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest22ActionPerformed

    private void quest13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest13ActionPerformed

    private void quest04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest04ActionPerformed

    private void quest30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest30ActionPerformed

    private void quest39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest39ActionPerformed

    private void quest25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest25ActionPerformed

    private void quest07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest07ActionPerformed

    private void quest16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest16ActionPerformed

    private void quest26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest26ActionPerformed

    private void quest08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest08ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest08ActionPerformed

    private void quest17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest17ActionPerformed

    private void quest43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest43ActionPerformed

    private void quest34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest34ActionPerformed

    private void quest06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest06ActionPerformed

    private void quest15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest15ActionPerformed

    private void quest24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest24ActionPerformed

    private void quest32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest32ActionPerformed

    private void quest41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest41ActionPerformed

    private void quest23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest23ActionPerformed

    private void quest14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest14ActionPerformed

    private void quest05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest05ActionPerformed

    private void quest29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest29ActionPerformed

    private void quest38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest38ActionPerformed

    private void quest31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest31ActionPerformed

    private void quest40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest40ActionPerformed

    private void quest33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest33ActionPerformed

    private void quest42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest42ActionPerformed

    private void quest35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest35ActionPerformed

    private void quest44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest44ActionPerformed

    private void quest09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest09ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest09ActionPerformed

    private void quest18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest18ActionPerformed

    private void quest27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest27ActionPerformed

    private void quest36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest36ActionPerformed

    private void quest45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quest45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quest45ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroGabarito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroGabarito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroGabarito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroGabarito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroGabarito dialog = new CadastroGabarito(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel jLObrigatorioNome;
    private javax.swing.JLabel jLObrigatorioNome10;
    private javax.swing.JLabel jLObrigatorioNome11;
    private javax.swing.JLabel jLObrigatorioNome12;
    private javax.swing.JLabel jLObrigatorioNome13;
    private javax.swing.JLabel jLObrigatorioNome14;
    private javax.swing.JLabel jLObrigatorioNome15;
    private javax.swing.JLabel jLObrigatorioNome16;
    private javax.swing.JLabel jLObrigatorioNome17;
    private javax.swing.JLabel jLObrigatorioNome18;
    private javax.swing.JLabel jLObrigatorioNome19;
    private javax.swing.JLabel jLObrigatorioNome2;
    private javax.swing.JLabel jLObrigatorioNome20;
    private javax.swing.JLabel jLObrigatorioNome21;
    private javax.swing.JLabel jLObrigatorioNome22;
    private javax.swing.JLabel jLObrigatorioNome23;
    private javax.swing.JLabel jLObrigatorioNome24;
    private javax.swing.JLabel jLObrigatorioNome25;
    private javax.swing.JLabel jLObrigatorioNome26;
    private javax.swing.JLabel jLObrigatorioNome27;
    private javax.swing.JLabel jLObrigatorioNome28;
    private javax.swing.JLabel jLObrigatorioNome29;
    private javax.swing.JLabel jLObrigatorioNome3;
    private javax.swing.JLabel jLObrigatorioNome30;
    private javax.swing.JLabel jLObrigatorioNome31;
    private javax.swing.JLabel jLObrigatorioNome32;
    private javax.swing.JLabel jLObrigatorioNome33;
    private javax.swing.JLabel jLObrigatorioNome34;
    private javax.swing.JLabel jLObrigatorioNome35;
    private javax.swing.JLabel jLObrigatorioNome36;
    private javax.swing.JLabel jLObrigatorioNome37;
    private javax.swing.JLabel jLObrigatorioNome38;
    private javax.swing.JLabel jLObrigatorioNome39;
    private javax.swing.JLabel jLObrigatorioNome4;
    private javax.swing.JLabel jLObrigatorioNome40;
    private javax.swing.JLabel jLObrigatorioNome41;
    private javax.swing.JLabel jLObrigatorioNome42;
    private javax.swing.JLabel jLObrigatorioNome43;
    private javax.swing.JLabel jLObrigatorioNome44;
    private javax.swing.JLabel jLObrigatorioNome45;
    private javax.swing.JLabel jLObrigatorioNome5;
    private javax.swing.JLabel jLObrigatorioNome6;
    private javax.swing.JLabel jLObrigatorioNome7;
    private javax.swing.JLabel jLObrigatorioNome8;
    private javax.swing.JLabel jLObrigatorioNome9;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jlNomeUsuario;
    private javax.swing.JLabel jlNomeUsuario10;
    private javax.swing.JLabel jlNomeUsuario11;
    private javax.swing.JLabel jlNomeUsuario12;
    private javax.swing.JLabel jlNomeUsuario13;
    private javax.swing.JLabel jlNomeUsuario14;
    private javax.swing.JLabel jlNomeUsuario15;
    private javax.swing.JLabel jlNomeUsuario16;
    private javax.swing.JLabel jlNomeUsuario17;
    private javax.swing.JLabel jlNomeUsuario18;
    private javax.swing.JLabel jlNomeUsuario19;
    private javax.swing.JLabel jlNomeUsuario2;
    private javax.swing.JLabel jlNomeUsuario20;
    private javax.swing.JLabel jlNomeUsuario21;
    private javax.swing.JLabel jlNomeUsuario22;
    private javax.swing.JLabel jlNomeUsuario23;
    private javax.swing.JLabel jlNomeUsuario24;
    private javax.swing.JLabel jlNomeUsuario25;
    private javax.swing.JLabel jlNomeUsuario26;
    private javax.swing.JLabel jlNomeUsuario27;
    private javax.swing.JLabel jlNomeUsuario28;
    private javax.swing.JLabel jlNomeUsuario29;
    private javax.swing.JLabel jlNomeUsuario3;
    private javax.swing.JLabel jlNomeUsuario30;
    private javax.swing.JLabel jlNomeUsuario31;
    private javax.swing.JLabel jlNomeUsuario32;
    private javax.swing.JLabel jlNomeUsuario33;
    private javax.swing.JLabel jlNomeUsuario34;
    private javax.swing.JLabel jlNomeUsuario35;
    private javax.swing.JLabel jlNomeUsuario36;
    private javax.swing.JLabel jlNomeUsuario37;
    private javax.swing.JLabel jlNomeUsuario38;
    private javax.swing.JLabel jlNomeUsuario39;
    private javax.swing.JLabel jlNomeUsuario4;
    private javax.swing.JLabel jlNomeUsuario40;
    private javax.swing.JLabel jlNomeUsuario41;
    private javax.swing.JLabel jlNomeUsuario42;
    private javax.swing.JLabel jlNomeUsuario43;
    private javax.swing.JLabel jlNomeUsuario44;
    private javax.swing.JLabel jlNomeUsuario45;
    private javax.swing.JLabel jlNomeUsuario5;
    private javax.swing.JLabel jlNomeUsuario6;
    private javax.swing.JLabel jlNomeUsuario7;
    private javax.swing.JLabel jlNomeUsuario8;
    private javax.swing.JLabel jlNomeUsuario9;
    private javax.swing.JTextField quest01;
    private javax.swing.JTextField quest02;
    private javax.swing.JTextField quest03;
    private javax.swing.JTextField quest04;
    private javax.swing.JTextField quest05;
    private javax.swing.JTextField quest06;
    private javax.swing.JTextField quest07;
    private javax.swing.JTextField quest08;
    private javax.swing.JTextField quest09;
    private javax.swing.JTextField quest10;
    private javax.swing.JTextField quest11;
    private javax.swing.JTextField quest12;
    private javax.swing.JTextField quest13;
    private javax.swing.JTextField quest14;
    private javax.swing.JTextField quest15;
    private javax.swing.JTextField quest16;
    private javax.swing.JTextField quest17;
    private javax.swing.JTextField quest18;
    private javax.swing.JTextField quest19;
    private javax.swing.JTextField quest20;
    private javax.swing.JTextField quest21;
    private javax.swing.JTextField quest22;
    private javax.swing.JTextField quest23;
    private javax.swing.JTextField quest24;
    private javax.swing.JTextField quest25;
    private javax.swing.JTextField quest26;
    private javax.swing.JTextField quest27;
    private javax.swing.JTextField quest28;
    private javax.swing.JTextField quest29;
    private javax.swing.JTextField quest30;
    private javax.swing.JTextField quest31;
    private javax.swing.JTextField quest32;
    private javax.swing.JTextField quest33;
    private javax.swing.JTextField quest34;
    private javax.swing.JTextField quest35;
    private javax.swing.JTextField quest36;
    private javax.swing.JTextField quest37;
    private javax.swing.JTextField quest38;
    private javax.swing.JTextField quest39;
    private javax.swing.JTextField quest40;
    private javax.swing.JTextField quest41;
    private javax.swing.JTextField quest42;
    private javax.swing.JTextField quest43;
    private javax.swing.JTextField quest44;
    private javax.swing.JTextField quest45;
    // End of variables declaration//GEN-END:variables
}
