/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atena.telas;

import atena.gabarito.Gabarito;
import atena.gabarito.GabaritoDAO;
import atena.processoseletivo.ProcessoSeletivo;
import atena.processoseletivo.ProcessoSeletivoDAO;
import atena.processoseletivo.ProcessoSeletivoTableModel;
import atena.usuario.Usuario;
import atena.usuario.UsuarioDAO;
import atena.usuario.UsuarioTableModel;
import atena.util.Util;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Karlos Oliveira
 */
public class RelatorioGeral extends javax.swing.JDialog {

    ProcessoSeletivo processoSeletivo = new ProcessoSeletivo();
    ProcessoSeletivoDAO processoSeletivoDAO = new ProcessoSeletivoDAO();
    Gabarito gabarito = new Gabarito();
    GabaritoDAO gabaritoDAO = new GabaritoDAO();

    /**
     * Creates new form TelaCadastroUsuario
     */
    public RelatorioGeral(java.awt.Frame parent, boolean modal) {
        initComponents();
        getRootPane().setDefaultButton(btSalvar);

        btLimparActionPerformed(null);
        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btVoltar1 = new javax.swing.JButton();
        btVoltar2 = new javax.swing.JButton();
        btVoltar3 = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(580, 380));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        btVoltar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btVoltar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/icon_curso.png"))); // NOI18N
        btVoltar1.setText("ADMINISTRAÇÃO");
        btVoltar1.setContentAreaFilled(false);
        btVoltar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltar1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btVoltar1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar1);
        btVoltar1.setBounds(0, 100, 200, 60);

        btVoltar2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/return.png"))); // NOI18N
        btVoltar2.setText("CIÊNCIAS CONTÁBEIS");
        btVoltar2.setContentAreaFilled(false);
        btVoltar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltar2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btVoltar2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btVoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar2);
        btVoltar2.setBounds(290, 260, 245, 50);

        btVoltar3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btVoltar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/ads.png"))); // NOI18N
        btVoltar3.setText("ANÁLISE DE SISTEMAS");
        btVoltar3.setContentAreaFilled(false);
        btVoltar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltar3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btVoltar3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btVoltar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltar3ActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar3);
        btVoltar3.setBounds(0, 160, 233, 60);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/return.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setContentAreaFilled(false);
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar);
        btVoltar.setBounds(10, 300, 90, 70);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/cad_proc_selet.png"))); // NOI18N
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        jLabel6.setMaximumSize(new java.awt.Dimension(580, 380));
        jLabel6.setMinimumSize(new java.awt.Dimension(580, 380));
        jLabel6.setPreferredSize(new java.awt.Dimension(580, 380));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 580, 380);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed

        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btVoltar1ActionPerformed

    private void btVoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btVoltar2ActionPerformed

    private void btVoltar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btVoltar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RelatorioGeral dialog = new RelatorioGeral(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVoltar;
    private javax.swing.JButton btVoltar1;
    private javax.swing.JButton btVoltar2;
    private javax.swing.JButton btVoltar3;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
