/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atena.telas;

import atena.gabarito.Gabarito;
import atena.gabarito.GabaritoDAO;
import atena.processoseletivo.ProcessoSeletivo;
import atena.processoseletivo.ProcessoSeletivoDAO;
import atena.processoseletivo.ProcessoSeletivoTableModel;
import atena.respostas.Respostas;
import atena.respostas.RespostasDAO;
import atena.usuario.Usuario;
import atena.usuario.UsuarioDAO;
import atena.usuario.UsuarioTableModel;
import atena.util.Util;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Karlos Oliveira
 */
public class RelatorioGeral extends javax.swing.JDialog {

    ProcessoSeletivo processoSeletivo = new ProcessoSeletivo();
    ProcessoSeletivoDAO processoSeletivoDAO = new ProcessoSeletivoDAO();
    Gabarito gabarito = new Gabarito();
    GabaritoDAO gabaritoDAO = new GabaritoDAO();
    Respostas respostas = new Respostas();
    RespostasDAO respostasDAO = new RespostasDAO();
    int pontos = 0;
    List<Respostas> ranking = new ArrayList<>();

    /**
     * Creates new form TelaCadastroUsuario
     */
    public RelatorioGeral(java.awt.Frame parent, boolean modal) {
        initComponents();

        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAdministracao = new javax.swing.JButton();
        btServicoSocial = new javax.swing.JButton();
        btContabeis = new javax.swing.JButton();
        btAnalise = new javax.swing.JButton();
        btDireito = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        btEnfermagem = new javax.swing.JButton();
        btEducacaoFisica = new javax.swing.JButton();
        btFisioterapia = new javax.swing.JButton();
        btPsicologia = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(680, 420));
        setMinimumSize(new java.awt.Dimension(680, 420));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(680, 420));
        setResizable(false);
        getContentPane().setLayout(null);

        btAdministracao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAdministracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/adm.png"))); // NOI18N
        btAdministracao.setText("ADMINISTRAÇÃO");
        btAdministracao.setContentAreaFilled(false);
        btAdministracao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAdministracao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btAdministracao.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btAdministracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdministracaoActionPerformed(evt);
            }
        });
        getContentPane().add(btAdministracao);
        btAdministracao.setBounds(20, 110, 200, 60);

        btServicoSocial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btServicoSocial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/servico_social.png"))); // NOI18N
        btServicoSocial.setText("SERVIÇO SOCIAL");
        btServicoSocial.setContentAreaFilled(false);
        btServicoSocial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btServicoSocial.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btServicoSocial.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btServicoSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btServicoSocialActionPerformed(evt);
            }
        });
        getContentPane().add(btServicoSocial);
        btServicoSocial.setBounds(460, 230, 200, 60);

        btContabeis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btContabeis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/contabeis.png"))); // NOI18N
        btContabeis.setText("CIÊNCIAS CONTÁBEIS");
        btContabeis.setContentAreaFilled(false);
        btContabeis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btContabeis.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btContabeis.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btContabeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContabeisActionPerformed(evt);
            }
        });
        getContentPane().add(btContabeis);
        btContabeis.setBounds(20, 230, 223, 60);

        btAnalise.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAnalise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/ads.png"))); // NOI18N
        btAnalise.setText("ANÁLISE DE SISTEMAS");
        btAnalise.setContentAreaFilled(false);
        btAnalise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAnalise.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btAnalise.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btAnalise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnaliseActionPerformed(evt);
            }
        });
        getContentPane().add(btAnalise);
        btAnalise.setBounds(20, 170, 233, 60);

        btDireito.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btDireito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/direito.png"))); // NOI18N
        btDireito.setText("DIREITO");
        btDireito.setContentAreaFilled(false);
        btDireito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDireito.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btDireito.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btDireito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDireitoActionPerformed(evt);
            }
        });
        getContentPane().add(btDireito);
        btDireito.setBounds(260, 110, 143, 60);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/return.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setContentAreaFilled(false);
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar);
        btVoltar.setBounds(0, 340, 90, 70);

        btEnfermagem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btEnfermagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/enfermagem.png"))); // NOI18N
        btEnfermagem.setText("ENFERMAGEM");
        btEnfermagem.setContentAreaFilled(false);
        btEnfermagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btEnfermagem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btEnfermagem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btEnfermagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnfermagemActionPerformed(evt);
            }
        });
        getContentPane().add(btEnfermagem);
        btEnfermagem.setBounds(260, 230, 180, 60);

        btEducacaoFisica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btEducacaoFisica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/educacao_fisica.png"))); // NOI18N
        btEducacaoFisica.setText("EDUCAÇÃO FÍSICA");
        btEducacaoFisica.setContentAreaFilled(false);
        btEducacaoFisica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btEducacaoFisica.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btEducacaoFisica.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btEducacaoFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEducacaoFisicaActionPerformed(evt);
            }
        });
        getContentPane().add(btEducacaoFisica);
        btEducacaoFisica.setBounds(260, 170, 210, 60);

        btFisioterapia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btFisioterapia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/fisioterapia.png"))); // NOI18N
        btFisioterapia.setText("FISIOTERAPIA");
        btFisioterapia.setContentAreaFilled(false);
        btFisioterapia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFisioterapia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btFisioterapia.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btFisioterapia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFisioterapiaActionPerformed(evt);
            }
        });
        getContentPane().add(btFisioterapia);
        btFisioterapia.setBounds(460, 110, 180, 60);

        btPsicologia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btPsicologia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/pscicologia.png"))); // NOI18N
        btPsicologia.setText("PSICOLOGIA");
        btPsicologia.setContentAreaFilled(false);
        btPsicologia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPsicologia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btPsicologia.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btPsicologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPsicologiaActionPerformed(evt);
            }
        });
        getContentPane().add(btPsicologia);
        btPsicologia.setBounds(460, 170, 170, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atena/imagens/tela_relatorio.png"))); // NOI18N
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        jLabel6.setMaximumSize(new java.awt.Dimension(680, 420));
        jLabel6.setMinimumSize(new java.awt.Dimension(680, 420));
        jLabel6.setPreferredSize(new java.awt.Dimension(680, 420));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 680, 420);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void calcularNota() {
        List<Respostas> listaRespostas;
        listaRespostas = (respostasDAO.listar());
        for (Respostas listaResposta : listaRespostas) {
            
        }
    }


    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btAdministracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdministracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAdministracaoActionPerformed

    private void btContabeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContabeisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btContabeisActionPerformed

    private void btAnaliseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnaliseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAnaliseActionPerformed

    private void btServicoSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btServicoSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btServicoSocialActionPerformed

    private void btDireitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDireitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDireitoActionPerformed

    private void btEducacaoFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEducacaoFisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEducacaoFisicaActionPerformed

    private void btEnfermagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnfermagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEnfermagemActionPerformed

    private void btFisioterapiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFisioterapiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFisioterapiaActionPerformed

    private void btPsicologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPsicologiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPsicologiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RelatorioGeral dialog = new RelatorioGeral(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdministracao;
    private javax.swing.JButton btAnalise;
    private javax.swing.JButton btContabeis;
    private javax.swing.JButton btDireito;
    private javax.swing.JButton btEducacaoFisica;
    private javax.swing.JButton btEnfermagem;
    private javax.swing.JButton btFisioterapia;
    private javax.swing.JButton btPsicologia;
    private javax.swing.JButton btServicoSocial;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
